apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: solution0004
  description: solution0004
  links:
    - url: https://solution0004-dev.ea.sdlc.k8s.cbrands.com/testcontext/api/message
      title: Solution API
      icon: dashboard
  annotations:
    github.com/project-slug: ConstellationBrands/solution0004
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: "app=solution0004"
    argocd/app-selector: "app=solution0004"
    jira/project-key: 
    #circleci.com/project-slug: github/ConstellationBrands/solution0004
    #jira/component: <example-component>
spec:
  type: service
  lifecycle: experimental
  owner: ConstellationBrands
  providesApis:
    - solution0004
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: solution0004
  description: solution0004
spec:
  type: openapi
  lifecycle: experimental
  owner: ConstellationBrands
  definition:
    $text: https://github.com/ConstellationBrands/solution0004/blob/main/swagger.yaml